export const WORKBOOK_IMPORT_STATUSES = Object.freeze({
  DRY_RUN: 'DRY_RUN',
  VALIDATED: 'VALIDATED',
  BLOCKED: 'BLOCKED',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  IMPORTING_DRAFTS: 'IMPORTING_DRAFTS',
  PARTIALLY_IMPORTED_DRAFTS: 'PARTIALLY_IMPORTED_DRAFTS',
  IMPORTED_DRAFTS: 'IMPORTED_DRAFTS',
  FAILED_DRAFT_IMPORT: 'FAILED_DRAFT_IMPORT',
  CANCELLED: 'CANCELLED',
});

export const WORKBOOK_IMPORT_PLANNABLE_STATUSES = Object.freeze(new Set([
  WORKBOOK_IMPORT_STATUSES.VALIDATED,
  WORKBOOK_IMPORT_STATUSES.READY_FOR_REVIEW,
]));

export const WORKBOOK_IMPORT_EXECUTABLE_STATUSES = Object.freeze(new Set([
  WORKBOOK_IMPORT_STATUSES.READY_FOR_REVIEW,
]));

export const WORKBOOK_IMPORT_IN_PROGRESS_STATUSES = Object.freeze(new Set([
  WORKBOOK_IMPORT_STATUSES.IMPORTING_DRAFTS,
]));

export const WORKBOOK_IMPORT_COMPLETED_STATUSES = Object.freeze(new Set([
  WORKBOOK_IMPORT_STATUSES.IMPORTED_DRAFTS,
]));
