export const TRADE_SCENARIO_IDS = Object.freeze({
  ALPHARD_HARARE: 'SCN-ALPHARD-HARARE-001',
  PARTS_CONTAINER: 'SCN-PARTS-CONTAINER-001',
  BYO_VEHICLE_SHIPPING: 'SCN-BYO-VEHICLE-SHIPPING-001',
});

export const TRADE_SCENARIO_ENVIRONMENTS = Object.freeze({
  LOCAL: 'local',
  TEST: 'test',
  STAGING: 'staging',
  DEMO: 'demo',
  PRODUCTION: 'production',
});

export const TRADE_SCENARIO_SOURCE_TYPES = Object.freeze({
  SYSTEM_GENERATED: 'SYSTEM_GENERATED',
  CARUP_TEMPLATE: 'CARUP_TEMPLATE',
  LEGACY_WORKBOOK: 'LEGACY_WORKBOOK',
  OPERATOR_ENTERED: 'OPERATOR_ENTERED',
  BUYER_SUBMITTED: 'BUYER_SUBMITTED',
  SELLER_SUBMITTED: 'SELLER_SUBMITTED',
  SUPPLIER_SUBMITTED: 'SUPPLIER_SUBMITTED',
  LOGISTICS_PROVIDER_SUBMITTED: 'LOGISTICS_PROVIDER_SUBMITTED',
  API_PROVIDER: 'API_PROVIDER',
  GOVERNMENT_SOURCE: 'GOVERNMENT_SOURCE',
  VERIFIED_DOCUMENT: 'VERIFIED_DOCUMENT',
  TEST_FIXTURE: 'TEST_FIXTURE',
  VERIFIED_SNAPSHOT: 'VERIFIED_SNAPSHOT',
});

export const TRADE_SCENARIO_FIXTURE_CLASSES = Object.freeze({
  TEST_FIXTURE: 'TEST_FIXTURE',
  VERIFIED_SNAPSHOT: 'VERIFIED_SNAPSHOT',
  GOVERNMENT_SOURCE: 'GOVERNMENT_SOURCE',
});

export const TRADE_SCENARIO_ASSERTION_TYPES = Object.freeze({
  DRY_RUN_CAN_IMPORT: 'DRY_RUN_CAN_IMPORT',
  SHEET_ROW_COUNT: 'SHEET_ROW_COUNT',
  QUOTE_COUNT_FOR_ORDER: 'QUOTE_COUNT_FOR_ORDER',
  QUOTE_STATUS: 'QUOTE_STATUS',
  QUOTE_CURRENCY: 'QUOTE_CURRENCY',
  ORDER_SERVICE_SCOPE: 'ORDER_SERVICE_SCOPE',
  ORDER_FIELD_PRESENT: 'ORDER_FIELD_PRESENT',
  ORDER_FIELD_ABSENT: 'ORDER_FIELD_ABSENT',
  IMPORT_PLAN_BLOCKED_COUNT: 'IMPORT_PLAN_BLOCKED_COUNT',
  PRODUCTION_FORBIDDEN: 'PRODUCTION_FORBIDDEN',
});

export const DEFAULT_SCENARIO_ALLOWED_ENVIRONMENTS = Object.freeze([
  TRADE_SCENARIO_ENVIRONMENTS.LOCAL,
  TRADE_SCENARIO_ENVIRONMENTS.TEST,
  TRADE_SCENARIO_ENVIRONMENTS.STAGING,
  TRADE_SCENARIO_ENVIRONMENTS.DEMO,
]);
