export const IMPORT_ORDER_STATUSES = Object.freeze({
  IMPORT_REQUESTED: 'IMPORT_REQUESTED',
  QUOTE_ISSUED: 'QUOTE_ISSUED',
  SELLER_ASSIGNED: 'SELLER_ASSIGNED',
  DOCUMENTS_PENDING: 'DOCUMENTS_PENDING',
  DOCUMENTS_VERIFIED: 'DOCUMENTS_VERIFIED',
  CONTAINER_BOOKED: 'CONTAINER_BOOKED',
  READY_FOR_LOADING: 'READY_FOR_LOADING',
  LOADED: 'LOADED',
  SHIPPED: 'SHIPPED',
  ARRIVED_AT_BORDER: 'ARRIVED_AT_BORDER',
  CUSTOMS_IN_PROGRESS: 'CUSTOMS_IN_PROGRESS',
  DUTY_PENDING: 'DUTY_PENDING',
  DUTY_PAID: 'DUTY_PAID',
  RELEASED: 'RELEASED',
  REGISTRATION_PENDING: 'REGISTRATION_PENDING',
  ROADWORTHINESS_PENDING: 'ROADWORTHINESS_PENDING',
  INSURANCE_PENDING: 'INSURANCE_PENDING',
  ZIMBABWE_READY: 'ZIMBABWE_READY',
  LOCAL_LISTING_ENABLED: 'LOCAL_LISTING_ENABLED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
  FLAGGED_FOR_REVIEW: 'FLAGGED_FOR_REVIEW',
});

export const IMPORT_ORDER_TERMINAL_STATUSES = Object.freeze([
  IMPORT_ORDER_STATUSES.COMPLETED,
  IMPORT_ORDER_STATUSES.CANCELLED,
  IMPORT_ORDER_STATUSES.DISPUTED,
]);

export const IMPORT_ORDER_TRANSITIONS = Object.freeze({
  [IMPORT_ORDER_STATUSES.IMPORT_REQUESTED]: [
    IMPORT_ORDER_STATUSES.QUOTE_ISSUED,
    IMPORT_ORDER_STATUSES.SELLER_ASSIGNED,
    IMPORT_ORDER_STATUSES.DOCUMENTS_PENDING,
    IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW,
    IMPORT_ORDER_STATUSES.CANCELLED,
  ],
  [IMPORT_ORDER_STATUSES.QUOTE_ISSUED]: [
    IMPORT_ORDER_STATUSES.SELLER_ASSIGNED,
    IMPORT_ORDER_STATUSES.DOCUMENTS_PENDING,
    IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW,
    IMPORT_ORDER_STATUSES.CANCELLED,
  ],
  [IMPORT_ORDER_STATUSES.SELLER_ASSIGNED]: [
    IMPORT_ORDER_STATUSES.DOCUMENTS_PENDING,
    IMPORT_ORDER_STATUSES.QUOTE_ISSUED,
    IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW,
    IMPORT_ORDER_STATUSES.CANCELLED,
  ],
  [IMPORT_ORDER_STATUSES.DOCUMENTS_PENDING]: [
    IMPORT_ORDER_STATUSES.DOCUMENTS_VERIFIED,
    IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW,
    IMPORT_ORDER_STATUSES.CANCELLED,
  ],
  [IMPORT_ORDER_STATUSES.DOCUMENTS_VERIFIED]: [
    IMPORT_ORDER_STATUSES.CONTAINER_BOOKED,
    IMPORT_ORDER_STATUSES.CUSTOMS_IN_PROGRESS,
    IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW,
    IMPORT_ORDER_STATUSES.CANCELLED,
  ],
  [IMPORT_ORDER_STATUSES.CONTAINER_BOOKED]: [
    IMPORT_ORDER_STATUSES.READY_FOR_LOADING,
    IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW,
    IMPORT_ORDER_STATUSES.CANCELLED,
  ],
  [IMPORT_ORDER_STATUSES.READY_FOR_LOADING]: [IMPORT_ORDER_STATUSES.LOADED, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.LOADED]: [IMPORT_ORDER_STATUSES.SHIPPED, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.SHIPPED]: [IMPORT_ORDER_STATUSES.ARRIVED_AT_BORDER, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.ARRIVED_AT_BORDER]: [IMPORT_ORDER_STATUSES.CUSTOMS_IN_PROGRESS, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.CUSTOMS_IN_PROGRESS]: [IMPORT_ORDER_STATUSES.DUTY_PENDING, IMPORT_ORDER_STATUSES.DUTY_PAID, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.DUTY_PENDING]: [IMPORT_ORDER_STATUSES.DUTY_PAID, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.DUTY_PAID]: [IMPORT_ORDER_STATUSES.RELEASED, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.RELEASED]: [IMPORT_ORDER_STATUSES.REGISTRATION_PENDING, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.REGISTRATION_PENDING]: [IMPORT_ORDER_STATUSES.ROADWORTHINESS_PENDING, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.ROADWORTHINESS_PENDING]: [IMPORT_ORDER_STATUSES.INSURANCE_PENDING, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.INSURANCE_PENDING]: [IMPORT_ORDER_STATUSES.ZIMBABWE_READY, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.ZIMBABWE_READY]: [IMPORT_ORDER_STATUSES.LOCAL_LISTING_ENABLED, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.LOCAL_LISTING_ENABLED]: [IMPORT_ORDER_STATUSES.COMPLETED, IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW],
  [IMPORT_ORDER_STATUSES.FLAGGED_FOR_REVIEW]: [
    IMPORT_ORDER_STATUSES.IMPORT_REQUESTED,
    IMPORT_ORDER_STATUSES.DOCUMENTS_PENDING,
    IMPORT_ORDER_STATUSES.CUSTOMS_IN_PROGRESS,
    IMPORT_ORDER_STATUSES.CANCELLED,
    IMPORT_ORDER_STATUSES.DISPUTED,
  ],
  [IMPORT_ORDER_STATUSES.COMPLETED]: [],
  [IMPORT_ORDER_STATUSES.CANCELLED]: [],
  [IMPORT_ORDER_STATUSES.DISPUTED]: [],
});

export const DOCUMENT_STATUSES = Object.freeze({
  MISSING: 'MISSING',
  UPLOADED: 'UPLOADED',
  OCR_EXTRACTED: 'OCR_EXTRACTED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  FLAGGED: 'FLAGGED',
});

export const CONTAINER_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  BOOKING_OPEN: 'BOOKING_OPEN',
  BOOKING_CLOSED: 'BOOKING_CLOSED',
  LOADING: 'LOADING',
  SHIPPED: 'SHIPPED',
  ARRIVED: 'ARRIVED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const RESERVATION_STATUSES = Object.freeze({
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
});

export const SHIPMENT_STATUSES = Object.freeze({
  PLANNED: 'PLANNED',
  BOOKED: 'BOOKED',
  LOADING: 'LOADING',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED: 'ARRIVED',
  CUSTOMS_HOLD: 'CUSTOMS_HOLD',
  RELEASED: 'RELEASED',
  COMPLETED: 'COMPLETED',
  EXCEPTION: 'EXCEPTION',
});
