export const WORKBOOK_IMPORT_ACTION_TYPES = Object.freeze({
  CREATE_DRAFT: 'CREATE_DRAFT',
  UPSERT_DRAFT: 'UPSERT_DRAFT',
  REVIEW_ONLY: 'REVIEW_ONLY',
  LEDGER_REQUIRED: 'LEDGER_REQUIRED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  BLOCKED: 'BLOCKED',
});

export const WORKBOOK_IMPORT_RISK_LEVELS = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
});

export const WORKBOOK_IMPORT_TARGET_TABLES = Object.freeze([
  'diaspora_trade_profiles',
  'diaspora_import_orders',
  'diaspora_import_quotes',
  'diaspora_trade_documents',
  'diaspora_container_shipments',
  'diaspora_cargo_reservations',
  'diaspora_shipments',
  'diaspora_compliance_reviews',
  'diaspora_payment_milestones',
  'diaspora_reputation_records',
  'diaspora_ai_commands',
]);

export const WORKBOOK_IMPORT_MAP = Object.freeze({
  TRADE_PROFILES: Object.freeze({
    targetTable: 'diaspora_trade_profiles',
    serviceOwner: 'diasporaTradeProfileService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.UPSERT_DRAFT,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.MEDIUM,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Trade profiles may be staged for reviewer verification only; workbook data cannot directly verify identities.',
  }),
  DIASPORA_IMPORT_ORDERS: Object.freeze({
    targetTable: 'diaspora_import_orders',
    serviceOwner: 'diasporaImportOrderService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.CREATE_DRAFT,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.MEDIUM,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Import orders may become draft order documents only; release and completion states are blocked.',
  }),
  IMPORT_QUOTES: Object.freeze({
    targetTable: 'diaspora_import_quotes',
    serviceOwner: 'diasporaImportOrderService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.UPSERT_DRAFT,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.LOW,
    requiresApproval: false,
    executionAllowedInPhase1E: false,
    rule: 'Quotes may be staged as draft/submitted quotes only; accepted quote selection is blocked.',
  }),
  TRADE_DOCUMENTS: Object.freeze({
    targetTable: 'diaspora_trade_documents',
    serviceOwner: 'diasporaDocumentService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.CREATE_DRAFT,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.MEDIUM,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Trade documents may stage metadata only; OCR and verification remain reviewer-controlled.',
  }),
  CONTAINER_SHIPMENTS: Object.freeze({
    targetTable: 'diaspora_container_shipments',
    serviceOwner: 'diasporaContainerService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.UPSERT_DRAFT,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.MEDIUM,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Container rows may be staged as drafts; capacity and lifecycle rules must be rechecked server-side.',
  }),
  CARGO_RESERVATIONS: Object.freeze({
    targetTable: 'diaspora_cargo_reservations',
    serviceOwner: 'diasporaReservationService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.CREATE_DRAFT,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.MEDIUM,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Cargo reservations may be staged as requests only; approval depends on live container state.',
  }),
  SHIPMENTS: Object.freeze({
    targetTable: 'diaspora_shipments',
    serviceOwner: 'diasporaShipmentService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.CREATE_DRAFT,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.MEDIUM,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Shipments may stage timeline drafts only; delivered and released states are blocked.',
  }),
  COMPLIANCE_REVIEWS: Object.freeze({
    targetTable: 'diaspora_compliance_reviews',
    serviceOwner: 'diasporaComplianceService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.REVIEW_ONLY,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.HIGH,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Compliance rows are review drafts only; approved or flag-cleared outcomes cannot come from workbook data.',
  }),
  PAYMENT_MILESTONES: Object.freeze({
    targetTable: 'diaspora_payment_milestones',
    serviceOwner: 'diasporaTradeService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.REVIEW_ONLY,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.HIGH,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Payment milestones may stage payment drafts only; paid, confirmed, and release states are blocked.',
  }),
  REPUTATION_RECORDS: Object.freeze({
    targetTable: 'diaspora_reputation_records',
    serviceOwner: 'diasporaReputationService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.REVIEW_ONLY,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.HIGH,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'Reputation rows are review-only and must not be created before a completed transaction.',
  }),
  AI_COMMAND_CENTER: Object.freeze({
    targetTable: 'diaspora_ai_commands',
    serviceOwner: 'diasporaAiCommandService',
    actionType: WORKBOOK_IMPORT_ACTION_TYPES.CREATE_DRAFT,
    riskLevel: WORKBOOK_IMPORT_RISK_LEVELS.HIGH,
    requiresApproval: true,
    executionAllowedInPhase1E: false,
    rule: 'AI commands may be staged only; high-risk commands require approval and no AI execution happens in Phase 1E.',
  }),
});

export const WORKBOOK_IMPORT_ALLOWED_TARGET_TABLES = Object.freeze(new Set(WORKBOOK_IMPORT_TARGET_TABLES));
