/**
 * Phase 7C — Structured reason-code taxonomy for identity-verification decisions.
 *
 * Every assessment, rejection, retry request, and escalation must carry a
 * deterministic reason code so the system can enforce policy, route cases, and
 * display correct applicant-facing guidance without relying on free text.
 */

export const REASON_CODES = {
  NON_DOCUMENT: {
    code: 'NON_DOCUMENT',
    severity: 'error',
    category: 'evidence',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The submitted images do not appear to contain a supported identity document.',
    internalDescription: 'Evidence classification determined the image does not contain an identity document.',
  },
  DOCUMENT_NOT_VISIBLE: {
    code: 'DOCUMENT_NOT_VISIBLE',
    severity: 'error',
    category: 'evidence',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'No identity document could be seen in the submitted images.',
    internalDescription: 'The image does not show a clearly visible identity document.',
  },
  DOCUMENT_TOO_SMALL: {
    code: 'DOCUMENT_TOO_SMALL',
    severity: 'error',
    category: 'evidence',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The identity document occupies too little of the image to be readable.',
    internalDescription: 'Document region in image is too small for reliable OCR.',
  },
  BLURRY: {
    code: 'BLURRY',
    severity: 'warn',
    category: 'quality',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The submitted images are too blurry to read. Please submit clearer photos.',
    internalDescription: 'Image blur score below acceptable threshold.',
  },
  GLARE: {
    code: 'GLARE',
    severity: 'warn',
    category: 'quality',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'Reflections or glare obscure parts of the document.',
    internalDescription: 'Image glare score above acceptable threshold.',
  },
  CROPPED: {
    code: 'CROPPED',
    severity: 'warn',
    category: 'quality',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The document appears cut off or incomplete in the image.',
    internalDescription: 'Document edges are cropped or incomplete.',
  },
  FRONT_BACK_DUPLICATE: {
    code: 'FRONT_BACK_DUPLICATE',
    severity: 'error',
    category: 'evidence',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The front and back images appear to be the same photograph.',
    internalDescription: 'Front and back image hashes are identical.',
  },
  SELFIE_DOCUMENT_DUPLICATE: {
    code: 'SELFIE_DOCUMENT_DUPLICATE',
    severity: 'error',
    category: 'evidence',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The selfie appears to be the same image as a document photo.',
    internalDescription: 'Selfie image hash matches a document side.',
  },
  UNSUPPORTED_DOCUMENT_TYPE: {
    code: 'UNSUPPORTED_DOCUMENT_TYPE',
    severity: 'warn',
    category: 'document',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The submitted document type is not currently supported.',
    internalDescription: 'Document type not in supported list.',
  },
  EXPIRED_DOCUMENT: {
    code: 'EXPIRED_DOCUMENT',
    severity: 'warn',
    category: 'document',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The submitted document has expired.',
    internalDescription: 'Document expiry date is in the past.',
  },
  UNREADABLE_DOCUMENT: {
    code: 'UNREADABLE_DOCUMENT',
    severity: 'warn',
    category: 'quality',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The document could not be read clearly. Please submit a clearer image.',
    internalDescription: 'Document image is unreadable by automated systems.',
  },
  OCR_PROVIDER_FAILED: {
    code: 'OCR_PROVIDER_FAILED',
    severity: 'error',
    category: 'system',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The verification system encountered a technical issue. Please try again.',
    internalDescription: 'OCR provider call failed or timed out.',
  },
  OCR_RESULT_UNTRUSTED: {
    code: 'OCR_RESULT_UNTRUSTED',
    severity: 'warn',
    category: 'extraction',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The automated reading could not be confirmed as reliable.',
    internalDescription: 'OCR result failed trust checks — fields are not confirmed.',
  },
  REQUIRED_FIELDS_MISSING: {
    code: 'REQUIRED_FIELDS_MISSING',
    severity: 'warn',
    category: 'extraction',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'Not all required identity fields could be read.',
    internalDescription: 'Required identity fields are missing from OCR result.',
  },
  ACCOUNT_DOCUMENT_MISMATCH: {
    code: 'ACCOUNT_DOCUMENT_MISMATCH',
    severity: 'error',
    category: 'identity',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The name on the document does not match the account holder name.',
    internalDescription: 'Account holder and document holder names do not match.',
  },
  DOCUMENT_SIDE_MISMATCH: {
    code: 'DOCUMENT_SIDE_MISMATCH',
    severity: 'warn',
    category: 'evidence',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'The front and back images may not be from the same document.',
    internalDescription: 'Front and back images appear to be from different documents.',
  },
  SUSPECTED_TAMPERING: {
    code: 'SUSPECTED_TAMPERING',
    severity: 'error',
    category: 'fraud',
    approveAllowed: false,
    resubmissionAllowed: false,
    rejectionTerminal: true,
    escalateAllowed: true,
    defaultApplicantGuidance: 'Verification could not be completed.',
    internalDescription: 'Evidence shows signs of digital tampering or manipulation.',
  },
  SUSPECTED_FRAUD: {
    code: 'SUSPECTED_FRAUD',
    severity: 'critical',
    category: 'fraud',
    approveAllowed: false,
    resubmissionAllowed: false,
    rejectionTerminal: true,
    escalateAllowed: true,
    defaultApplicantGuidance: 'Verification could not be completed.',
    internalDescription: 'Multiple indicators suggest fraudulent activity.',
  },
  TECHNICAL_ERROR: {
    code: 'TECHNICAL_ERROR',
    severity: 'error',
    category: 'system',
    approveAllowed: false,
    resubmissionAllowed: true,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'A system error occurred. Please try again later.',
    internalDescription: 'Unexpected technical error during processing.',
  },
  SPECIALIST_REVIEW_REQUIRED: {
    code: 'SPECIALIST_REVIEW_REQUIRED',
    severity: 'warn',
    category: 'escalation',
    approveAllowed: false,
    resubmissionAllowed: false,
    rejectionTerminal: false,
    escalateAllowed: true,
    defaultApplicantGuidance: 'Additional review is needed before a decision can be made.',
    internalDescription: 'Case requires specialist or manual escalation review.',
  },
  OTHER: {
    code: 'OTHER',
    severity: 'info',
    category: 'other',
    approveAllowed: true,
    resubmissionAllowed: true,
    rejectionTerminal: true,
    escalateAllowed: true,
    defaultApplicantGuidance: 'Verification requires attention.',
    internalDescription: 'Manual reason provided by reviewer.',
  },
};

export function getReasonConfig(code) {
  return REASON_CODES[code] || REASON_CODES.OTHER;
}

export const REASON_CODE_LIST = Object.keys(REASON_CODES);

export const SEVERITY_ORDER = ['critical', 'error', 'warn', 'info'];

export function severityScore(severity) {
  const idx = SEVERITY_ORDER.indexOf(severity);
  return idx >= 0 ? idx : SEVERITY_ORDER.length;
}
