import test from 'node:test';
import assert from 'node:assert/strict';
import {getVehicleTaxonomyCatalog,normalizeVehicleTaxonomyInput,resolveColor,resolveFuelType,resolveTransmission,resolveVehicleMake,resolveVehicleModel,resolveVehicleYear} from '../services/taxonomy/vehicleTaxonomyService.js';
test('global vehicle taxonomy is one versioned platform catalog',()=>{const c=getVehicleTaxonomyCatalog();assert.equal(c.version,'carup-global-vehicle-taxonomy@1.0.0');assert.ok(c.makes.length>30);assert.ok(c.makes.every(m=>m.id.startsWith('make:')));assert.ok(c.makes.flatMap(m=>m.models).every(m=>m.id.startsWith('model:')))});
test('regional aliases resolve without verifying a vehicle fact',()=>{assert.equal(resolveVehicleMake('VW').canonical_label,'Volkswagen');const jazz=resolveVehicleModel('Honda','Jazz');assert.equal(jazz.state,'alias_match');assert.equal(jazz.canonical_id,'model:honda:fit')});
test('colour, fuel and transmission vocabulary close Sell/Buy parity gaps',()=>{assert.equal(resolveColor('Gray').canonical_label,'Grey');assert.equal(resolveFuelType('PHEV').canonical_label,'Plug-in Hybrid');assert.equal(resolveTransmission('CVT').canonical_label,'CVT');assert.equal(resolveTransmission('DSG').canonical_label,'DCT')});
test('unknown values stay unresolved rather than guessed',()=>{const make=resolveVehicleMake('Unknown Coachworks');assert.equal(make.state,'unrecognized');assert.equal(make.raw,'Unknown Coachworks');const model=resolveVehicleModel('Toyota','Mystery 9000');assert.equal(model.state,'unrecognized');assert.equal(model.raw,'Mystery 9000')});
test('one year policy is shared by authoring and discovery',()=>{const now=new Date('2026-08-28T00:00:00Z');assert.equal(resolveVehicleYear(2027,now).state,'canonical');assert.equal(resolveVehicleYear(1886,now).state,'canonical');assert.equal(resolveVehicleYear(1885,now).state,'unrecognized');assert.equal(resolveVehicleYear(2028,now).state,'unrecognized')});
test('normalization remains separate from verification authority',()=>{const r=normalizeVehicleTaxonomyInput({make:'VW',model:'Polo',year:2020,fuel_type:'Gasoline',transmission:'Auto',drivetrain:'Front Wheel Drive',category:'Hatchback',condition:'Pre-Owned'});assert.equal(r.taxonomy_version,'carup-global-vehicle-taxonomy@1.0.0');assert.equal(r.make.canonical_label,'Volkswagen');assert.equal(r.fuel.canonical_label,'Petrol');assert.equal(r.transmission.canonical_label,'Automatic');assert.equal(r.drivetrain.canonical_label,'FWD');assert.equal(r.body_style.canonical_label,'Hatchback');assert.equal(r.seller_condition.canonical_label,'Used')});
