/**
 * Public truth on the marketing surfaces.
 *
 * These four pages are what a stranger reads before they trust CarUp with a car
 * purchase, and they carried the programme's most consequential fabrications:
 * institutional integrations that do not exist, a custody claim that contradicts
 * the product, statistics with no source, demo personas presented as the
 * company's leadership — and, worst of all, two forms that announced success
 * while discarding what a person typed.
 *
 * The submission defect is the one that could cause real harm. Somebody reporting
 * a stolen vehicle or a fraudulent dealer was shown a ticket number generated by
 * `Math.random()` and told CarUp had it in hand. Nothing was stored and nothing
 * was sent.
 *
 * Assertions run over COMMENT-STRIPPED source, because each page now documents
 * what it removed and why — a whole-file search would flag the explanation as if
 * it were the claim.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, '../..');

const codeOnly = (source) => source
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/\{\/\*[\s\S]*?\*\/\}/g, '')
  .replace(/^\s*\/\/.*$/gm, '');

const read = (rel) => codeOnly(fs.readFileSync(path.join(REPO, rel), 'utf8'));

const TRUST = read('web/src/pages/TrustSafety.tsx');
const ABOUT = read('web/src/pages/About.tsx');
const HELP = read('web/src/pages/HelpCenter.tsx');
const CONTACT = read('web/src/pages/Contact.tsx');

const PAGES = [
  ['TrustSafety.tsx', TRUST],
  ['About.tsx', ABOUT],
  ['HelpCenter.tsx', HELP],
  ['Contact.tsx', CONTACT],
];

// ── No form may claim a success it did not achieve ─────────────────────────

test('no public form fabricates a successful submission', () => {
  for (const [name, source] of PAGES) {
    assert.ok(!/toast\.success\(\s*['"`][^'"`]*(sent|submitted|logged|received)/i.test(source),
      `${name} must not announce a delivery it did not make`);
    // The exact shape of the defect: a timer standing in for a request.
    assert.ok(!/setTimeout\([^)]*\)\s*=>\s*\{[^}]*toast\.success/s.test(source),
      `${name} must not resolve a timer and call it a success`);
  }
});

test('TrustSafety generates no ticket number and promises no response time', () => {
  assert.ok(!/Math\.random\(\)/.test(TRUST), 'a ticket number invented client-side is not a ticket');
  assert.ok(!/TK-ZIM-/.test(TRUST));
  assert.ok(!/Response SLA|Under 2 Hours|High Priority Audit/i.test(TRUST));
  assert.ok(!/dispatched to/i.test(TRUST), 'no email was ever dispatched');
});

test('the TrustSafety report action is disabled and says why', () => {
  assert.ok(TRUST.includes('trust-report-unavailable'));
  assert.ok(TRUST.includes('trust-report-submit'));
  assert.ok(/disabled/.test(TRUST.split('trust-report-submit')[1].slice(-400) + TRUST.split('trust-report-submit')[0].slice(-400)),
    'the submit control must be disabled');
  assert.ok(/support@carup\.co\.zw/.test(TRUST), 'a channel that genuinely exists must be offered instead');
});

test('the Contact form is disabled and says why', () => {
  assert.ok(CONTACT.includes('contact-unavailable'));
  assert.ok(CONTACT.includes('contact-submit'));
  assert.ok(/support@carup\.co\.zw/.test(CONTACT));
  assert.ok(!/within 24 hours/i.test(CONTACT), 'no reply time may be promised for a form that cannot send');
});

// ── No institutional integration may be asserted ───────────────────────────

test('no page claims a live registry or revenue-authority integration', () => {
  // provider_registry is empty and every registry check on record ran against a
  // sandbox simulator, so any live-sync claim is unsupportable.
  const forbidden = [
    /real-time digital sync/i,
    /cross-reference[^.]{0,80}(ZINARA|CVR|ZIMRA)/i,
    /query the live ZINARA/i,
    /CVR registers the update/i,
    /registry synchronization/i,
    /ZINARA\s*&\s*CVR Sync/i,
  ];
  for (const [name, source] of PAGES) {
    for (const pattern of forbidden) {
      assert.ok(!pattern.test(source), `${name} must not assert ${pattern}`);
    }
  }
});

test('no page presents an authority or a bank as a partner', () => {
  assert.ok(!/Partners:\s*CVR/i.test(TRUST));
  for (const [name, source] of PAGES) {
    assert.ok(!/CABS|Stanbic/.test(source), `${name} must not name a bank as an integration`);
  }
});

// ── No custody claim ───────────────────────────────────────────────────────

test('no page claims CarUp holds funds', () => {
  for (const [name, source] of PAGES) {
    assert.ok(!/regulated trust account/i.test(source), `${name} must not claim a trust account`);
    assert.ok(!/regulated banking partners/i.test(source), `${name} must not claim banking partners`);
    assert.ok(!/funds are (safely |securely )?held/i.test(source), `${name} must not claim custody of funds`);
  }
  // And the true position is stated, since CarUp is non-custodial by design.
  assert.ok(/non-custodial|does not hold, transfer or process/i.test(TRUST));
});

// ── No unsupported quantitative claim ──────────────────────────────────────

test('the adjudicated fabricated statistics do not reappear', () => {
  // Each of these was already removed elsewhere in the repo as fabricated.
  const figures = ['98.7%', '99.8%', '12,000+', '10,000+', '850+', '4x more engagement'];
  for (const [name, source] of PAGES) {
    for (const figure of figures) {
      assert.ok(!source.includes(figure), `${name} must not publish the fabricated figure ${figure}`);
    }
  }
});

test('no page publishes a service-level or turnaround promise', () => {
  for (const [name, source] of PAGES) {
    assert.ok(!/within 48 hours/i.test(source), `${name} must not promise a 48-hour audit`);
    assert.ok(!/under 3 hours/i.test(source), `${name} must not publish a turnaround time`);
    assert.ok(!/monitor[^.]{0,40}24\/7|available 24\/7|24\/7 (support|monitoring)/i.test(source),
      `${name} must not promise continuous availability`);
  }
});

// ── No unsupported inspection, KYC or capability claim ─────────────────────

test('no page claims biometric or face-match identity verification', () => {
  for (const [name, source] of PAGES) {
    // A page stating there is NO biometric check is doing the right thing, so the
    // assertion targets the affirmative claim rather than the word.
    assert.ok(!/(require|requires|all uploads require|using|with)\s+(a\s+)?(face-match|biometric)/i.test(source),
      `${name} must not claim a biometric check`);
    assert.ok(!/Biometric face-match KYC/i.test(source), `${name} must not advertise biometric KYC`);
  }
});

test('TrustSafety claims no physical inspection network or ECU tooling', () => {
  for (const claim of ['150-Point Inspection', 'ECU scanner', 'Proprietary ECU', 'master mechanics']) {
    assert.ok(!TRUST.includes(claim), `TrustSafety must not claim ${claim}`);
  }
});

test('TrustSafety does not describe the internal ledger as a blockchain or immutable', () => {
  // The I0 audit established this is an internal signature ledger, and its own
  // appendix says not to describe it as a blockchain in stakeholder documents.
  // "not a blockchain" is the correction, so the assertion targets the claim.
  assert.ok(!/(is|as|onto|hashed onto) (a |the )?blockchain/i.test(TRUST));
  assert.ok(!/immutable digital identity ledger/i.test(TRUST));
  assert.ok(!/Immutable Certificate Hash/i.test(TRUST));
});

// ── About: no demo persona may be presented as a real person ───────────────

test('About names no fabricated executive', () => {
  for (const persona of ['Tendai Moyo', 'Sarah Chikomo', 'James Ncube', 'Ayesha Khan']) {
    assert.ok(!ABOUT.includes(persona), `${persona} is demo persona data and must not appear as leadership`);
  }
  assert.ok(!/Leadership Team/.test(ABOUT), 'the section is removed until there is a real roster');
});

test('About makes no market-primacy claim', () => {
  assert.ok(!/Zimbabwe's first/i.test(ABOUT));
});

// ── Placeholder contact details are not published as real ──────────────────

test('no page publishes a placeholder address or phone number as real', () => {
  for (const [name, source] of PAGES) {
    assert.ok(!/123 Samora Machel/i.test(source), `${name} must not publish a placeholder address`);
    assert.ok(!/\+263 242 700 000/.test(source), `${name} must not publish a placeholder phone number`);
  }
});

// ── The orphaned intake is recorded, not silently wired ────────────────────

test('the fraud-report destination table remains unwired, and deliberately so', () => {
  const backend = fs.readdirSync(path.join(REPO, 'backend/routes'))
    .map((f) => fs.readFileSync(path.join(REPO, 'backend/routes', f), 'utf8'))
    .join('\n');
  // `marketplace_listing_reports` exists in staging AND production but has no
  // route, no service and no reviewer queue. Writing to it without a queue would
  // create a hole reports fall into unseen — worse than an honest refusal.
  assert.ok(!backend.includes('marketplace_listing_reports'),
    'wiring an intake with no reviewer surface would hide reports rather than handle them');
});
