import crypto from 'crypto';
import { supabase } from '../../db/supabase.js';
import { getTrustDecision } from '../trustDecision/trustDecisionService.js';
import { requestEscrow } from '../escrow/escrowTrustService.js';
import { ConflictError, NotFoundError, UnauthorizedError, ValidationError } from '../../utils/errors.js';

/** Issue #164 Phase 6: purchase inquiry -> resolved participants -> transaction intent -> eligibility. */
export const MARKETPLACE_TRANSACTION_VEHICLE_SELECT = ['vin','owner_id','current_seller_id','tenant_id','publication_status','price','currency','currency_source','updated_at'].join(',');
const TRANSACTION_INQUIRY_SELECT='id, listing_id, buyer_id, seller_id, inquiry_type, status, risk_status, created_at';
const CURRENT_PURCHASE_INQUIRY_STATUSES=new Set(['new','assigned','contacted','qualified']);
function recordedText(value){const text=String(value??'').trim();return text.length?text:null;}
export function resolveMarketplaceSellerId(vehicle={}){return recordedText(vehicle.current_seller_id)||recordedText(vehicle.owner_id);}
export function resolveMarketplaceListingTerms(vehicle={}){const amount=Number(vehicle.price);const currency=recordedText(vehicle.currency)?.toUpperCase()||null;const currencySource=recordedText(vehicle.currency_source);if(!Number.isFinite(amount)||amount<=0)throw new ValidationError('This listing has no server-authoritative transaction amount.');if(!currency||!currencySource)throw new ValidationError('This listing has no provenance-backed transaction currency.');return{amount,currency,currencySource};}
export function isCurrentPurchaseInquiry(inquiry={}, {vin,buyerId,sellerId}={}){return inquiry.inquiry_type==='vehicle_purchase_interest'&&inquiry.listing_id===vin&&inquiry.buyer_id===buyerId&&inquiry.seller_id===sellerId&&inquiry.risk_status==='clear'&&CURRENT_PURCHASE_INQUIRY_STATUSES.has(inquiry.status);}
export async function loadCurrentPurchaseInquiry(vin,buyerId,sellerId,client=supabase){const{data,error}=await client.from('marketplace_inquiries').select(TRANSACTION_INQUIRY_SELECT).eq('listing_id',vin).eq('buyer_id',buyerId).eq('inquiry_type','vehicle_purchase_interest').order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(!data||!isCurrentPurchaseInquiry(data,{vin,buyerId,sellerId}))throw new ConflictError('A current clear purchase inquiry with this seller is required before starting a transaction.');return data;}
export function buildMarketplaceListingSnapshot(vehicle={},sellerId,terms){return crypto.createHash('sha256').update(JSON.stringify({vin:vehicle.vin||null,seller_id:sellerId||null,publication_status:vehicle.publication_status||null,amount:terms?.amount??null,currency:terms?.currency??null,currency_source:terms?.currencySource??null,listing_updated_at:vehicle.updated_at||null})).digest('hex');}
export function buildMarketplaceEscrowGateContext(decision={}){const d=decision.dimensions||{};return{identity_status:d.identity?.status||'not_evaluated',publication_status:d.publication_eligibility?.status||d.publication_eligibility?.value||'not_evaluated',fraud_block:d.fraud_risk?.status==='high'?true:d.fraud_risk?.status==='clear'?false:null,seller_suspended:d.dealer_compliance?.status==='suspended'?true:['compliant','not_evaluated'].includes(d.dealer_compliance?.status)?false:null,participant_authorized:true,required_documents_present:d.evidence_completeness?.status==='complete',listing_snapshot_changed:false};}
export function buildCanonicalTransactionKey({vin,buyerId,sellerId,inquiryId,listingSnapshotHash,gateContext}){return crypto.createHash('sha256').update(JSON.stringify({contract:'marketplace-transaction-v1',vin,buyerId,sellerId,inquiryId,listingSnapshotHash,gateContext})).digest('hex');}
export function toPublicMarketplaceEscrowSession(session={}){return{transaction_intent_id:session.id||null,vin:session.vin||null,status:session.status||null,listing_amount:session.listing_amount==null?null:Number(session.listing_amount),listing_currency:session.listing_currency||null,gate_reasons:Array.isArray(session.gate_reasons)?session.gate_reasons:[],payment_state:session.escrow_id?'provider_intent_linked':'not_started',created_at:session.created_at||null,updated_at:session.updated_at||null};}
export async function loadMarketplaceTransactionVehicle(vin,client=supabase){const{data,error}=await client.from('vehicles').select(MARKETPLACE_TRANSACTION_VEHICLE_SELECT).eq('vin',vin).maybeSingle();if(error)throw error;if(!data)throw new NotFoundError('Listing not found.');return data;}
export async function requestMarketplaceEscrow(vin,{actor,client=supabase}={}){const buyerId=recordedText(actor?.id||actor?.userId);if(!buyerId)throw new UnauthorizedError('A verified buyer identity is required.');const vehicle=await loadMarketplaceTransactionVehicle(vin,client);if(String(vehicle.publication_status||'').toLowerCase()!=='published')throw new ConflictError('This listing is not available to start a new transaction.');const sellerId=resolveMarketplaceSellerId(vehicle);if(!sellerId)throw new ValidationError('The listing seller could not be resolved server-side.');if(sellerId===buyerId)throw new ConflictError('Buyer and seller must be different participants.');const inquiry=await loadCurrentPurchaseInquiry(vin,buyerId,sellerId,client);const terms=resolveMarketplaceListingTerms(vehicle);const decision=await getTrustDecision(vin);const gateContext=buildMarketplaceEscrowGateContext(decision);const listingSnapshotHash=buildMarketplaceListingSnapshot(vehicle,sellerId,terms);const idempotencyKey=buildCanonicalTransactionKey({vin,buyerId,sellerId,inquiryId:inquiry.id,listingSnapshotHash,gateContext});const session=await requestEscrow(vin,{buyerId,sellerId,inquiryId:inquiry.id,gateContext,idempotencyKey,listingSnapshotHash,listingTerms:terms},{id:buyerId,role:actor?.role||actor?.effectiveRole||'buyer'},{client});return toPublicMarketplaceEscrowSession(session);}
export default{MARKETPLACE_TRANSACTION_VEHICLE_SELECT,resolveMarketplaceSellerId,resolveMarketplaceListingTerms,isCurrentPurchaseInquiry,loadCurrentPurchaseInquiry,buildMarketplaceListingSnapshot,buildMarketplaceEscrowGateContext,buildCanonicalTransactionKey,toPublicMarketplaceEscrowSession,loadMarketplaceTransactionVehicle,requestMarketplaceEscrow};
